package nl.brickx.domain.Models;

public enum MenuItemIdentifier {
    LOCATION_INFO_ITEM,
    PRODUCT_INFO_ITEM,
    ORDER_PICK_ITEM,
    BATCH_PICK_ITEM,
    INCOMING_GOODS_ITEM,
    STOCK_MUTATION_ITEM,
    STOCK_TRANSFER_ITEM,
    STOCK_COUNT_ITEM,
    SSCC_ITEM,
    GENERATE_LABEL_ITEM,
    REPLENISHMENT_ITEM
}
